apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-repo1-deployment
  labels:
    app: test-repo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-repo1
  template:
    metadata:
      labels:
        app: test-repo1
    spec:
      containers:
        - name: test-repo1
          image: test-repo1:latest
          ports:
            - containerPort: 5000
