name: PR Integration Test for Repo1

on:
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run Tests
        run: python -m unittest discover

      # Build Docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/test-repo1:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/test-repo1:latest

      # Trigger Kube-Test Pipeline
      - name: Trigger Kube-Test Pipeline
        id: kube_test_trigger
        run: |
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.KUBE_TEST_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/rlghks-aiofarm/kube-test/dispatches \
            -d '{"event_type": "pr-integration-test", "client_payload": {"updated_repo": "test-repo1"}}')

          echo "Kube-Test triggered, checking status..."
          # Ensure no output errors
          echo "::set-output name=trigger_status::success"

      # Fetch the Latest Run ID from kube-test
      - name: Fetch Kube-Test Run ID
        id: fetch_run_id
        run: |
          run_id=$(curl -H "Authorization: token ${{ secrets.KUBE_TEST_TOKEN }}" \
            https://api.github.com/repos/rlghks-aiofarm/kube-test/actions/runs \
            | jq -r '.workflow_runs | sort_by(.created_at) | reverse | .[0].id')

          echo "Latest run ID is $run_id"
          echo "::set-output name=run_id::$run_id"

      # Poll Kube-Test Pipeline status
      - name: Check Kube-Test Pipeline status
        run: |
          run_id=${{ steps.fetch_run_id.outputs.run_id }}
          status="in_progress"
          max_retries=30
          retry_count=0
          sleep_time=10

          while [[ "$status" == "in_progress" ]] || [[ "$status" == "queued" ]]; do
            if [[ $retry_count -ge $max_retries ]]; then
              echo "Kube-Test did not complete within the expected time. Exiting."
              exit 1
            fi

            status_response=$(curl -H "Authorization: token ${{ secrets.KUBE_TEST_TOKEN }}" \
              https://api.github.com/repos/rlghks-aiofarm/kube-test/actions/runs/$run_id)

            status=$(echo "$status_response" | jq -r '.conclusion')

            echo "Current status: $status"
            if [[ "$status" == "success" ]]; then
              echo "Kube-Test passed successfully."
              exit 0
            elif [[ "$status" == "failure" ]]; then
              echo "Kube-Test failed. Exiting workflow."
              exit 1
            fi

            echo "Waiting for 10 seconds before retrying..."
            ((retry_count++))
            sleep $sleep_time
          done

      # # Deploy to Kubernetes
      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: 'v1.26.0'

      # - name: Deploy to Kubernetes
      #   env:
      #     KUBECONFIG: ${{ secrets.KUBECONFIG }}
      #   run: |
      #     kubectl apply -f k8s/deployment.yaml
      #     kubectl apply -f k8s/service.yaml
